### ISSUE TITLE
how to achieve sample biden's same level?

### ISSUE THREAD

**Issue by friendmine** [gitmylo/bark-voice-cloning-HuBERT-quantizer#10]
how to achieve sample biden's same level?
i used some voice of biden's, 
but can't get the same level with example !

**Comment by gitmylo** [comment]
Use a clean sample clip, [voicemod's website](https://tuna.voicemod.net/search/sounds/) has some pretty good clips for example.

Make sure there's as little noise as possible, no background music and such.

**Comment by friendmine** [comment]
thanks for your answer, 
I did't got a good result.
btw: I made a mistake, I've installed the bark, the npz path, shoud be a virtual env's .
