### ISSUE TITLE
can not find tokenizer.pth in GitMylo/bark-voice-cloning

### ISSUE THREAD

**Issue by Autonomof** [gitmylo/bark-voice-cloning-HuBERT-quantizer#11]
as the title, so how can I do? Thanks

**Comment by gitmylo** [comment]
use the [HubertManager](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer/blob/master/hubert/hubert_manager.py) for easy downloading of HuBERT and tokenizer models
