### ISSUE TITLE
Hubert with portuguese

### ISSUE THREAD

**Issue by gab-luz** [gitmylo/bark-voice-cloning-HuBERT-quantizer#12]
I've found this HuBert model in portuguese. How do I load it with your tool?
The generated voices are in English, of course, but they are very similar to the real ones. 
https://huggingface.co/jonatasgrosman/exp_w2v2t_pt_hubert_s486
![image](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer/assets/109997891/607c70f0-a536-4d73-b919-e3334c6c2c89)

_Originally posted by @gab-luz in https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer/issues/6#issuecomment-1564324332_

**Comment by gab-luz** [comment]
I'm cloning voices in English but I can't make them work in Portuguese. Perhaps that hubert base model from the first post might help me, but I can't load it with your tool.

**Comment by gitmylo** [comment]
I'm only using the start of HuBERT, audio to semantic vectors. I don't think it matters much which language you use there, so you can just use the HuBERT base model.

It's the quantizer (the model this repo is about) that matters, You'll need to train one
