### ISSUE TITLE
ModuleNotFoundError: No module named 'hubert'

### ISSUE THREAD

**Issue by Barth44** [gitmylo/bark-voice-cloning-HuBERT-quantizer#14]
The colab notebook says ModuleNotFoundError: No module named 'hubert' and when I try to install hubert manually I get ooking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement HuBERT (from versions: none)
ERROR: No matching distribution found for HuBERT.

**Comment by gitmylo** [comment]
HuBERT is a module in this repository, the notebook does not work on its own, it wasn't tested on colab.
I could add a git clone to make it work in colab though.

**Comment by gitmylo** [comment]
Added [Google Colab compatible notebook](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer/blob/master/colab_notebook.ipynb) in commit 32b104a
