### ISSUE TITLE
German tokenizer available / overtraining

### ISSUE THREAD

**Issue by C0untFloyd** [gitmylo/bark-voice-cloning-HuBERT-quantizer#15]
Hey Mylo, thanks for your work on enabling Bark voice cloning and documenting everything you did. I can't believe you just started with machine learning!

I successfully trained a german tokenizer which is available here:
[https://huggingface.co/CountFloyd/bark-voice-cloning-german-HuBERT-quantizer](https://huggingface.co/CountFloyd/bark-voice-cloning-german-HuBERT-quantizer)

It was trained for 14 epochs with quantizer version 1. The input dataset is right here:
[https://huggingface.co/datasets/CountFloyd/bark-german-semantic-wav-training](https://huggingface.co/datasets/CountFloyd/bark-german-semantic-wav-training)

So far results are pretty good, however I'm wondering if it's possible to overtrain. In your example code you're always using the model trained for 14 epochs, not the one trained longer for 23 epochs. Shouldn't the latter one be better? Are there reasons to stop training earlier to prevent e.g. overfitting?

Anyway, please also check out my [Bark Repo](https://github.com/C0untFloyd/bark-gui) where I wrapped your code in a Gradio GUI. It's also possible to swap voices in audio and train with it although this is still WIP. Thanks again!

**Comment by gitmylo** [comment]
I'm guessing you used HuBERT base, if not, please tell me which model you used, so i can correct it in the readme.

i have not noticed any overtraining on 23 epochs, but the 23 epoch model is larger in filesize, so the default is the smaller model. Results are noticably better though.

Cool GUI, i personally use [my own GUI](/gitmylo/audio-webui)

**Comment by xiabo2011** [comment]
@C0untFloyd Do you use hubert_base_ls960.pt for German?

**Comment by C0untFloyd** [comment]
Yes I did 👍

**Comment by xiabo2011** [comment]
@C0untFloyd how is the voice clone effect?
