### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Smartking1** [gitmylo/bark-voice-cloning-HuBERT-quantizer#20]
I have successfully run the colab notebook and saved the speaker.npz file. 
The issue now is how do I test it on a new data

**Comment by gitmylo** [comment]
What do you mean by that?

**Comment by Smartking1** [comment]
how do I test the clone on a text data

**Comment by gitmylo** [comment]
Use bark to generate it and use the npz as the speaker file.

An easy gui which lets you do this for example: https://github.com/gitmylo/audio-webui
But you could also just set the speaker file in the official bark repository.

**Comment by Smartking1** [comment]
Thanks
Is there a sample code to generate it with bark or a guide to do that

**Comment by gitmylo** [comment]
under this section of the bark readme: https://github.com/suno-ai/bark/tree/main#-voice-presets

**Comment by gitmylo** [comment]
instead of putting a preset speaker name, you can put the path to your npz file

**Comment by Smartking1** [comment]
Thanks so much
I have also launched the web_ui interface on Gradio

Which of the options can I use for voice cloning

**Comment by gitmylo** [comment]
on the text to speech tab, you can select bark

there's also rvc speech conversion, which takes audio as the input, and replaces the voice, but you need to train that one.

**Comment by Smartking1** [comment]
Alright
Working now
