### ISSUE TITLE
Question:how do i use the trained quantizer in the original bark project?

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [gitmylo/bark-voice-cloning-HuBERT-quantizer#29]
If I am correct we need to train a custom HuBERT model and then load it into the bark project?

from https://github.com/suno-ai/bark
I only see history_prompt argument as the official way of pseudo voice clone tone.so I am slightly confused.@@

**Comment by gitmylo** [comment]
This repo creates a history prompt which can be used in bark.

There's some info in the readme which shows how to create a history prompt you can give bark [here](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer#how-do-i-clone-a-voice)

[Or you could write the code to create it yourself](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer#for-developers-implementing-voice-cloning-in-your-bark-projects)

**Comment by Meatfucker** [comment]
How do you actually integrate this with bark though? The example code you provided leaves you with a variable called semantic_tokens and no indication of how to use it. Can we pass that as history_prompt?

**Comment by gitmylo** [comment]
The semantic tokens are saved together with the coarse and fine tokens into a .npz file, with numpy.savez(). The file that is created can be loaded into bark.
