### ISSUE TITLE
How to create a quantizer in a dialect that Bark didn't support?

### ISSUE THREAD

**Issue by Naozumi520** [gitmylo/bark-voice-cloning-HuBERT-quantizer#48]
Cantonese, a dialect from China. Often used by Hong Kong people and GuangZhou. The problem is, Bark only support "Chinese", which is Putonghua in fact. 

I would like to create a Cantonese quantizer from beginning, how am I suppose to do that? As I know, like @junwchina said, `bark-data-gen` is a tool used to generate training data and train my quantizer model. But the pronunciation of Cantonese and Putonghua is completely different. If I use `bark-data-gen`, it will likely only output a Putonghua dataset, which is not the one I want.

**Comment by junwchina** [comment]
Sorry, I didn't check the supported languages of Bark. I'm afraid voice cloning in Cantonese is currently not possible until Bark adds support for the Cantonese language.

**Comment by Naozumi520** [comment]
Oh I see... That's such a shame.... Thank you for telling me anyway! :D
