### ISSUE TITLE
How to Train for Non-Verbal Effects Voice?

### ISSUE THREAD

**Issue by boringtaskai** [gitmylo/bark-voice-cloning-HuBERT-quantizer#52]
How do I train for keyword effects, such as [man], [woman], or even how do I train for [music] keyword?

Do I have to put [man] on semantic text, to train man voice? 

Really appreciate for you work

**Comment by gitmylo** [comment]
That isn't possible, This model doesn't train bark, it just creates data that bark can read and continue with the same voice.

**Comment by boringtaskai** [comment]
Oh okay, thanks, I understand now
