### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by ege-adam** [gitmylo/bark-voice-cloning-HuBERT-quantizer#55]
[https://huggingface.co/egeadam/bark-voice-cloning-turkish-HuBERT-quantizer](url)

Here HuBERT training for Turkish language. It is trained from open source books, but I won't be sharing dataset since I don't have redistribute rights. It is trained with 14 epoch, results are ok. Further improvement can be done using RVC over bark.

**Comment by boringtaskai** [comment]
Hi can you share, what GPU do you use or what provider do you use? and how many hours to train the model? Since I want to rent a gpu, and calculate the budget

**Comment by ege-adam** [comment]
Model is trained on single rtx 3090. 12GB GPU from Google Colab might be enough. I just put it for training overnight(5~ hours), it was trained around 22 epochs. Then I decided 14 epoch is good. BUT IT TAKES TIME(1 day~) AND REQUIRES GPU TO GENERATE DATASET.  Also please be aware that it has been few months since I trained this model, so my numbers might be wrong. It took a while to get permissions from writers for the books in the dataset and release the model.

**Comment by gitmylo** [comment]
Feel free to create a PR [here](https://github.com/gitmylo/Voice-cloning-quantizers). Once it's been merged it will show up in audio-webui and any other services which use this list for obtaining available models.

**Comment by ege-adam** [comment]
I've created the pull request, thank you for your work!
