### ISSUE TITLE
another language?

### ISSUE THREAD

**Issue by HobisPL** [gitmylo/bark-voice-cloning-HuBERT-quantizer#6]
How to use it for a different language? 
Because it keeps speaking in English. 
I used this notebook on Google Colab.
https://colab.research.google.com/drive/1IA3c_R859nANerMARazCSrjc2UD3ws8A?usp=sharing#scrollTo=bRvO6RstRpMX

**Comment by gitmylo** [comment]
The pretrained model is English only. To get other languages you'll need to train (or finetune) a quantizer model yourself.

**Comment by HobisPL** [comment]
How can you train such a model, what data is needed, etc.?

**Comment by gitmylo** [comment]
data zips can be created with https://github.com/gitmylo/bark-data-gen, but you'll have to change the "books" which contains sources, and you may have to change the allowed chars as well if your language does not use the a-z alphabet.

i also have the dataset which i created to train the current model uploaded on huggingface https://huggingface.co/datasets/GitMylo/bark-semantic-training

when you have created that, zip up your semantic files (.npz) and you audio files (.wav) and put those zips in a folder for example "example" here:

Your semantics zip goes in `example/semantic/test.zip`

Your audio zip goes in `example/wav/test.zip`

You can have more than one zip, but make sure their names match, so test.zip in semantic has the semantics for test.zip in wav

[Prepare, train and then test](https://huggingface.co/datasets/GitMylo/bark-semantic-training)

**Comment by gitmylo** [comment]
transcriptions aren't the same as semantics, you need actual semantics.

you could generate from the transcriptions of the common voice dataset. ignoring the actual audio files and using bark-generated audio files instead.

for https://github.com/gitmylo/bark-data-gen you need some links to text, and it will load it into memory and cut out chunks and generate from them.

**Comment by HobisPL** [comment]
I'm not sure if I understand correctly. Instead of using books, can I use transcriptions based on audio files, and I won't need to generate wavs using Bark? Do I just need to name the files properly, like npy and wav? What I mean is that the files generated by Bark are of low quality, and some of them don't sound in my language.

**Comment by gitmylo** [comment]
you **do** need to generate wavs yourself. otherwise they won't match. but transcripts can be used to create the semantics which then get turned into the wavs.

if some files generated don't sound like your language, then that's a bark issue. and this voice cloning cannot go beyond what bark can. as it relies on bark in order to create the training data.

**Comment by gitmylo** [comment]
You would need to finetune bark, which isn't possible with this repository. There are a lot of steps you would need to take, and i'm personally still trying to figure that out.

**Comment by gitmylo** [comment]
i believe you can use hubert_base_ls960.pt. I believe it works for other languages.

once you've trained a bit and think it's good enough, it would be really cool if you could upload it to huggingface, and i could make a list of different models people have made for different languages etc.

**Comment by HobisPL** [comment]
Where should I put the path to this model if I'm getting an error when I place the path here?

`tokenizer = CustomTokenizer.load_from_checkpoint('/content/bark-voice-cloning-HuBERT-quantizer/tokenizer.pth')`

RuntimeError: [enforce fail at inline_container.cc:257] . file in archive is not in a subdirectory model_epoch_52/:
model_epoch_52.pth/.info

Did something go wrong with the training?

**Comment by gitmylo** [comment]
open the model_epoch_52 as a zip, move the .info file from the model folder into the model_epoch_52 folder.

i'll fix this for the future

**Comment by gab-luz** [comment]
I've found this HuBert model in portuguese:
https://huggingface.co/jonatasgrosman/exp_w2v2t_pt_hubert_s486
![image](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer/assets/109997891/607c70f0-a536-4d73-b919-e3334c6c2c89)

**Comment by gitmylo** [comment]
Original checkpoints are from https://github.com/facebookresearch/fairseq/tree/main/examples/hubert
There is no difference in bin vs pt vs pth etc. they're both pickle files that can be viewed as a zip as well. You can check if you are able to load the model, it might work.

**Comment by HobisPL** [comment]
I have tested it, it cannot copy the style. It can speak Polish well, which the limited BARK cannot do well. I tested a model with 7 epochs, I don't know if changing it to 20 epochs would make any difference.

**Comment by gitmylo** [comment]
usually results get decent around 4 epochs (with 8 hours of training data), if it sounds nothing like what you want at that point, it probably won't get much better.

**Comment by HobisPL** [comment]
It works very well, the voice is very close to the original, but there's an issue with mimicking a person's style, meaning if a person has a speech impediment, for example, it cannot replicate that. It probably requires training the model further, which is currently not possible.

**Comment by gitmylo** [comment]
right, that might improve with some extra training, but not a whole lot. Speech impediments is definitely something bark in general struggles with.

**Comment by HobisPL** [comment]
Would it be necessary to use such data, with various pronunciation flaws, etc., to train the HuBERT model?

**Comment by gitmylo** [comment]
you don't train the HuBERT model, you train the quantizer for the HuBERT model. it's only used for creating the history prompt, you can't really go beyond what bark can do. and i'm not sure bark is very good at this.

**Comment by HobisPL** [comment]
I have checked, and the whole recording is 8 hours long, but many samples have a lot of silence. For example, speech lasts for 3 seconds, while silence/noise lasts for 10 seconds. Some samples don't sound like Polish at all.
Is it possible to use the model I created for further generation? Does this model generate better samples, or does it no longer make sense?

**Comment by gitmylo** [comment]
Bark itsself still has issues with other languages. If that's the case, it's not something I can easily fix.

**Comment by HobisPL** [comment]
Yes, BARK speaks weakly in other languages, but after training with HuBERT-quantizer, it speaks much better.

**Comment by gitmylo** [comment]
Do you mean the clones speak better in other languages than bark does without the clones?

**Comment by HobisPL** [comment]
Yes, maybe because BARK recognizes the language itself, and it does it incorrectly.

**Comment by HobisPL** [comment]
> i believe you can use hubert_base_ls960.pt. I believe it works for other languages.
> 
> once you've trained a bit and think it's good enough, it would be really cool if you could upload it to huggingface, and i could make a list of different models people have made for different languages etc.

https://huggingface.co/spaces/Hobis/bark-voice-cloning-polish-HuBERT-quantizer

**Comment by gitmylo** [comment]
Nice! It would be better if you uploaded it as a model separately as well though, instead of as a space. Once you do that, i'll make a list of the models.

**Comment by gitmylo** [comment]
*ps*: If you upload the dataset to huggingface, tell me, so i can add it to the info.

If we end up with a lot of datasets, we could merge them and train a multilingual model. Which would be even better!

**Comment by HobisPL** [comment]
dataset:
https://huggingface.co/datasets/Hobis/bark-polish-semantic-wav-training/tree/main
The term "semantic" encompasses more than just WAV files, but that is not a problem because it will still generate a compatible number with the WAV files.
model:
https://huggingface.co/Hobis/bark-voice-cloning-polish-HuBERT-quantizer


> _ps_: If you upload the dataset to huggingface, tell me, so i can add it to the info.
> 
> If we end up with a lot of datasets, we could merge them and train a multilingual model. Which would be even better!

**Comment by xiabo2011** [comment]
@HobisPL did you use hubert_base_ls960.pt for training data generation? From this link https://github.com/facebookresearch/fairseq/tree/main/examples/hubert I saw Hubert base was trained with [Librispeech](http://www.openslr.org/12) which is an English dataset.

**Comment by Maverick1983** [comment]
@HobisPL Same question...
